name: Build

on:
  workflow_dispatch:
    inputs:
      runner:
        description: "Runner"
        required: true
        type: string
        default: "ubuntu-latest" 
  schedule:
    - cron: "0 0 */16 * *"

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      build: ${{ steps.check.outputs.build }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-tags: true
      - id: check
        run: |
          echo "build=true" >> "$GITHUB_OUTPUT"

  build:
    needs: check
    if: needs.check.outputs.build == 'true'
    runs-on: ${{ github.event_name == 'workflow_dispatch' && inputs.runner || 'self-hosted' }}
    steps:
      - uses: actions/checkout@v5

      - name: Set ENV
        run: |
          chmod +x *.sh
          echo "VERSION=$(date '+%Y.%m.%d')" >> $GITHUB_ENV

      - name: Build
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          ./build.sh

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: v${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          files: |
            boot_arm64only.img
            recovery_arm64only.img
            recovery_arm64only-userdebug.img
            android/lineage/out/target/product/virtio_arm64only/*ota.zip
            android/lineage/out/target/product/virtio_arm64only/VirtualMachine/UTM/UTM-VM*.zip
            boot_x86_64.img
            recovery_x86_64.img
            recovery_x86_64-userdebug.img
            android/lineage/out/target/product/virtio_x86_64/*ota.zip
            android/lineage/out/target/product/virtio_x86_64/VirtualMachine/UTM/UTM-VM*.zip

      - name: Attest
        uses: actions/attest@v4
        with:
          subject-path: |
            boot_arm64only.img
            recovery_arm64only.img
            recovery_arm64only-userdebug.img
            android/lineage/out/target/product/virtio_arm64only/*ota.zip
            android/lineage/out/target/product/virtio_arm64only/VirtualMachine/UTM/UTM-VM*.zip
            boot_x86_64.img
            recovery_x86_64.img
            recovery_x86_64-userdebug.img
            android/lineage/out/target/product/virtio_x86_64/*ota.zip
            android/lineage/out/target/product/virtio_x86_64/VirtualMachine/UTM/UTM-VM*.zip
